### ISSUE TITLE
Swap hardcorded portablegabi version with corresponding npm badge 

### ISSUE THREAD

**Issue by wischli** [KILTprotocol/portablegabi-tutorial#8]
To easily always show the current portablegabi version, we should swap the current hardcoded 0.0.2 with a badge, if possible.

We should also add a checkmark to the portablegabi PR template, that the tutorial will be adjusted according to the changes if necessary.

**Comment by wischli** [comment]
@weichweich What do you think?

**Comment by weichweich** [comment]
I think that would be nice. But i would only include the current version if the tutorial is tested with the current version.

Not sure what it takes but having the tutorials tested would be super cool. We should also consider to merge this repository into the portablegabi repository
